import Mathlib

/-!
# Characteristic-two anisotropicity of simplicial spheres

This file states that every positive-dimensional simplicial sphere is
generically anisotropic over every field of characteristic two.
-/

section

/-!
# The generic Artinian reduction of a simplicial complex

This file fixes the objects occurring in Definitions 2.2 and 3.2 of
Papadakis--Petrotou.  Vertices are indexed by `Fin m`; this is only the
zero-based version of the paper's vertex set `{1, ..., m}`.

The grading on a quotient is represented extensionally: a quotient class is
homogeneous of degree `j` when it has a homogeneous polynomial representative
of degree `j`.  Once homogeneity of the defining ideal has been developed,
this agrees with membership in the degree-`j` graded component.
-/

noncomputable section

open scoped BigOperators

namespace SimplicialSphereAnisotropicity

open MvPolynomial

section Sphere

/-- The support of a barycentric coordinate vector. -/
def barycentricSupport {m : ℕ} (x : Fin m → ℝ) : Finset (Fin m) :=
  Finset.univ.filter fun v ↦ x v ≠ 0

/--
The canonical geometric realization of a finite abstract simplicial complex:
nonnegative barycentric coordinate vectors of total mass one whose support is
a face.
-/
def geometricRealization {m : ℕ} (D : AbstractSimplicialComplex (Fin m)) :
    Set (Fin m → ℝ) :=
  {x | (∀ v, 0 ≤ x v) ∧ (∑ v, x v) = 1 ∧ barycentricSupport x ∈ D}

/-- `D` has combinatorial dimension exactly `n`. -/
def HasDimension {m : ℕ} (D : AbstractSimplicialComplex (Fin m)) (n : ℕ) : Prop :=
  (∀ s : Finset (Fin m), s ∈ D → s.card ≤ n + 1) ∧
    ∃ s : Finset (Fin m), s ∈ D ∧ s.card = n + 1

/--
A finite simplicial sphere of dimension `n`.

The topological condition uses the canonical barycentric realization and the
unit sphere in `ℝ^(n+1)`, i.e. the standard `n`-sphere.  The explicit
dimension clause records the paper's combinatorial dimension convention.
-/
def IsSimplicialSphere {m : ℕ} (D : AbstractSimplicialComplex (Fin m)) (n : ℕ) : Prop :=
  HasDimension D n ∧
    Nonempty
      (geometricRealization D ≃ₜ
        Metric.sphere (0 : EuclideanSpace ℝ (Fin (n + 1))) 1)

end Sphere

section Reduction

variable (k₁ : Type*) [Field k₁]

/-- The polynomial ring `k₁[a_(i,j)]` of generic coefficients. -/
abbrev CoefficientPolynomial (n m : ℕ) :=
  MvPolynomial (Fin (n + 1) × Fin m) k₁

/-- The purely transcendental coefficient field `k₁(a_(i,j))`. -/
abbrev GenericField (n m : ℕ) :=
  FractionRing (CoefficientPolynomial k₁ n m)

/-- The coefficient `a_(i,j)` in the generic coefficient field. -/
def genericCoefficient {n m : ℕ} (i : Fin (n + 1)) (j : Fin m) :
    GenericField k₁ n m :=
  algebraMap (CoefficientPolynomial k₁ n m) (GenericField k₁ n m)
    (MvPolynomial.X (i, j))

/-- The square-free monomial attached to a set of vertices. -/
def faceMonomial {K : Type*} [CommSemiring K] {m : ℕ} (s : Finset (Fin m)) :
    MvPolynomial (Fin m) K :=
  ∏ v ∈ s, MvPolynomial.X v

/--
The Stanley--Reisner ideal, generated by the square-free monomials belonging
to nonempty nonfaces of `D`.
-/
def stanleyReisnerIdeal {K : Type*} [CommSemiring K] {m : ℕ}
    (D : AbstractSimplicialComplex (Fin m)) : Ideal (MvPolynomial (Fin m) K) :=
  Ideal.span
    {p | ∃ s : Finset (Fin m), s.Nonempty ∧ s ∉ D ∧ p = faceMonomial s}

/-- The generic degree-one parameter `f_i = Σ_j a_(i,j) x_j`. -/
def genericLinearForm {n m : ℕ} (i : Fin (n + 1)) :
    MvPolynomial (Fin m) (GenericField k₁ n m) :=
  ∑ j : Fin m, MvPolynomial.C (genericCoefficient k₁ i j) * MvPolynomial.X j

/-- The ideal generated by all `n+1` generic linear parameters. -/
def genericParameterIdeal (n m : ℕ) :
    Ideal (MvPolynomial (Fin m) (GenericField k₁ n m)) :=
  Ideal.span (Set.range (genericLinearForm k₁ (n := n) (m := m)))

/-- The Stanley--Reisner and generic-parameter relations together. -/
def genericReductionIdeal {n m : ℕ} (D : AbstractSimplicialComplex (Fin m)) :
    Ideal (MvPolynomial (Fin m) (GenericField k₁ n m)) :=
  stanleyReisnerIdeal D ⊔ genericParameterIdeal k₁ n m

/-- The paper's generic Artinian reduction `A`. -/
abbrev GenericArtinianReduction {n m : ℕ} (D : AbstractSimplicialComplex (Fin m)) :=
  MvPolynomial (Fin m) (GenericField k₁ n m) ⧸ genericReductionIdeal k₁ D

/-- A class in `A` lying in its homogeneous component of degree `j`. -/
def IsHomogeneousClass {n m : ℕ} (D : AbstractSimplicialComplex (Fin m))
    (j : ℕ) (u : GenericArtinianReduction k₁ (n := n) D) : Prop :=
  ∃ p : MvPolynomial (Fin m) (GenericField k₁ n m),
    p.IsHomogeneous j ∧
      Ideal.Quotient.mk (genericReductionIdeal k₁ D) p = u

/--
Definition 3.2: every nonzero homogeneous class through half the socle degree
has nonzero square.
-/
def GenericallyAnisotropic {m : ℕ} (D : AbstractSimplicialComplex (Fin m))
    (n : ℕ) : Prop :=
  ∀ j : ℕ, 1 ≤ j → 2 * j ≤ n + 1 →
    ∀ u : GenericArtinianReduction k₁ (n := n) D,
      IsHomogeneousClass k₁ D j u → u ≠ 0 → u ^ 2 ≠ 0

end Reduction

end SimplicialSphereAnisotropicity

end

end

section

/-!
# The theorem statement
-/

namespace SimplicialSphereAnisotropicity

/-- Characteristic-two generic anisotropicity of a positive-dimensional
simplicial sphere. -/
theorem characteristic_two_anisotropicity
    (k₁ : Type*) [Field k₁] [CharP k₁ 2]
    {n m : ℕ} (hn : 1 ≤ n)
    (D : AbstractSimplicialComplex (Fin m)) (hD : IsSimplicialSphere D n) :
    GenericallyAnisotropic k₁ D n := by
  sorry

end SimplicialSphereAnisotropicity


end
